### ISSUE TITLE
Can't close connection

### ISSUE THREAD

**Issue by asherber** [linq2db/linq2db.LINQPad#94]
Using the default LINQ to SQL driver for Sql Server, the `Connection` object in a LinqPad script starts out in a closed state and can be opened and closed as needed. But using the Linq2db driver (for a Postgres database), `Connection` starts out in an open state -- and it appears that calling `Close()` has no effect.

```csharp
Connection.State.Dump();   // Open
Connection.Close();
Connection.State.Dump();   // Open
```

Is there a way to either get the connection to start closed, or to close it by hand?

**Comment by MaceWindu** [comment]
It looks like LinqPAD behavior to me.

All we do is create and return connection instance to LinqPAD [here](https://github.com/linq2db/linq2db.LINQPad/blob/master/Source/Drivers/DynamicLinqToDBDriver.cs#L241)

I've made some tests:
```cs
Connection.GetHashCode().Dump();
Connection.State.Dump();
Connection.Close();
Connection.State.Dump();
Connection.GetHashCode().Dump();
```

```
54897010
Open
Open
54897010
```

if I save connection to variable to avoid Connection property access I get expected behavior:

```cs
var cn = Connection;
cn.GetHashCode().Dump();
cn.State.Dump();
cn.Close();
cn.State.Dump();
cn.GetHashCode().Dump();
```

```
21201098
Open
Closed
21201098
```

I suspect Connection property implementation by LinqPAD opens connection if it is not opened on invoke. I would recommend to ask on LinqPAD forum if it is an issue for you as I don't see currently how we can affect this behavior from driver

**Comment by asherber** [comment]
Thanks, that's interesting. I assumed it was a driver issue because the behavior is different if I use the LINQ to SQL driver to connect SQL Server, or if I use Npgsql directly.
